//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2011 SarvSoft.
        /// </summary>
        public static string app_copyright {
            get {
                return ResourceManager.GetString("app_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome .
        /// </summary>
        public static string app_welcome {
            get {
                return ResourceManager.GetString("app_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disable.
        /// </summary>
        public static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string edit_role {
            get {
                return ResourceManager.GetString("edit_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string edit_user {
            get {
                return ResourceManager.GetString("edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;nable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price details.
        /// </summary>
        public static string frm_title_base_price_editor {
            get {
                return ResourceManager.GetString("frm_title_base_price_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member details.
        /// </summary>
        public static string frm_title_member_editor {
            get {
                return ResourceManager.GetString("frm_title_member_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule details.
        /// </summary>
        public static string frm_title_rule_editor {
            get {
                return ResourceManager.GetString("frm_title_rule_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group details.
        /// </summary>
        public static string frm_title_tour_Cost_group_editor {
            get {
                return ResourceManager.GetString("frm_title_tour_Cost_group_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour details.
        /// </summary>
        public static string frm_title_tour_editor {
            get {
                return ResourceManager.GetString("frm_title_tour_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string gpx_updates {
            get {
                return ResourceManager.GetString("gpx_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost type.
        /// </summary>
        public static string grid_title_Cost_type {
            get {
                return ResourceManager.GetString("grid_title_Cost_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string grid_title_participants {
            get {
                return ResourceManager.GetString("grid_title_participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per person.
        /// </summary>
        public static string grid_title_price_per_person {
            get {
                return ResourceManager.GetString("grid_title_price_per_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed up.
        /// </summary>
        public static string grid_title_signup_count {
            get {
                return ResourceManager.GetString("grid_title_signup_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SigneUp type.
        /// </summary>
        public static string grid_title_signup_type {
            get {
                return ResourceManager.GetString("grid_title_signup_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string grid_title_time {
            get {
                return ResourceManager.GetString("grid_title_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour type.
        /// </summary>
        public static string grid_title_tour_type {
            get {
                return ResourceManager.GetString("grid_title_tour_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Loading....
        /// </summary>
        public static string lbl_app_loading {
            get {
                return ResourceManager.GetString("lbl_app_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to workbench.
        /// </summary>
        public static string lbl_back_to_workbench {
            get {
                return ResourceManager.GetString("lbl_back_to_workbench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string lbl_category {
            get {
                return ResourceManager.GetString("lbl_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string lbl_comments {
            get {
                return ResourceManager.GetString("lbl_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraints.
        /// </summary>
        public static string lbl_constraints {
            get {
                return ResourceManager.GetString("lbl_constraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string lbl_contacts {
            get {
                return ResourceManager.GetString("lbl_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Rules.
        /// </summary>
        public static string lbl_cost_rules {
            get {
                return ResourceManager.GetString("lbl_cost_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string lbl_current_version {
            get {
                return ResourceManager.GetString("lbl_current_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lbl_date {
            get {
                return ResourceManager.GetString("lbl_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string lbl_db_name {
            get {
                return ResourceManager.GetString("lbl_db_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbl_db_password {
            get {
                return ResourceManager.GetString("lbl_db_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number.
        /// </summary>
        public static string lbl_db_port {
            get {
                return ResourceManager.GetString("lbl_db_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        public static string lbl_db_server {
            get {
                return ResourceManager.GetString("lbl_db_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lbl_db_srv_user {
            get {
                return ResourceManager.GetString("lbl_db_srv_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string lbl_employees {
            get {
                return ResourceManager.GetString("lbl_employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string lbl_first_name {
            get {
                return ResourceManager.GetString("lbl_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string lbl_formula {
            get {
                return ResourceManager.GetString("lbl_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string lbl_group {
            get {
                return ResourceManager.GetString("lbl_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Rules.
        /// </summary>
        public static string lbl_group_rules {
            get {
                return ResourceManager.GetString("lbl_group_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string lbl_groups {
            get {
                return ResourceManager.GetString("lbl_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest contacts.
        /// </summary>
        public static string lbl_guest_contacts {
            get {
                return ResourceManager.GetString("lbl_guest_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string lbl_guests {
            get {
                return ResourceManager.GetString("lbl_guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string lbl_last_name {
            get {
                return ResourceManager.GetString("lbl_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked.
        /// </summary>
        public static string lbl_last_update_check {
            get {
                return ResourceManager.GetString("lbl_last_update_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Contacts.
        /// </summary>
        public static string lbl_member_contacts {
            get {
                return ResourceManager.GetString("lbl_member_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lbl_notes {
            get {
                return ResourceManager.GetString("lbl_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string lbl_participants {
            get {
                return ResourceManager.GetString("lbl_participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string lbl_payment_amount {
            get {
                return ResourceManager.GetString("lbl_payment_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType.
        /// </summary>
        public static string lbl_payment_type {
            get {
                return ResourceManager.GetString("lbl_payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Price.
        /// </summary>
        public static string lbl_price {
            get {
                return ResourceManager.GetString("lbl_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produced by.
        /// </summary>
        public static string lbl_produced_by {
            get {
                return ResourceManager.GetString("lbl_produced_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered to.
        /// </summary>
        public static string lbl_registered_to {
            get {
                return ResourceManager.GetString("lbl_registered_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string lbl_roles {
            get {
                return ResourceManager.GetString("lbl_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name.
        /// </summary>
        public static string lbl_rule_name {
            get {
                return ResourceManager.GetString("lbl_rule_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Served people.
        /// </summary>
        public static string lbl_served {
            get {
                return ResourceManager.GetString("lbl_served", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name.
        /// </summary>
        public static string lbl_service_name {
            get {
                return ResourceManager.GetString("lbl_service_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string lbl_services {
            get {
                return ResourceManager.GetString("lbl_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up count.
        /// </summary>
        public static string lbl_signup_count {
            get {
                return ResourceManager.GetString("lbl_signup_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up type.
        /// </summary>
        public static string lbl_signup_type {
            get {
                return ResourceManager.GetString("lbl_signup_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string lbl_tasks {
            get {
                return ResourceManager.GetString("lbl_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string lbl_time {
            get {
                return ResourceManager.GetString("lbl_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lbl_title {
            get {
                return ResourceManager.GetString("lbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Costs.
        /// </summary>
        public static string lbl_tour_costs {
            get {
                return ResourceManager.GetString("lbl_tour_costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string lbl_tour_group_name {
            get {
                return ResourceManager.GetString("lbl_tour_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Members.
        /// </summary>
        public static string lbl_tour_members {
            get {
                return ResourceManager.GetString("lbl_tour_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Prices.
        /// </summary>
        public static string lbl_tour_prices {
            get {
                return ResourceManager.GetString("lbl_tour_prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lbl_tour_status {
            get {
                return ResourceManager.GetString("lbl_tour_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lbl_tour_type {
            get {
                return ResourceManager.GetString("lbl_tour_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        public static string lbl_tours {
            get {
                return ResourceManager.GetString("lbl_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string lbl_types {
            get {
                return ResourceManager.GetString("lbl_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic update.
        /// </summary>
        public static string lbl_upd_auto_check {
            get {
                return ResourceManager.GetString("lbl_upd_auto_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new version automatically.
        /// </summary>
        public static string lbl_upd_auto_download {
            get {
                return ResourceManager.GetString("lbl_upd_auto_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates every.
        /// </summary>
        public static string lbl_upd_interval {
            get {
                return ResourceManager.GetString("lbl_upd_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string lbl_upd_sseconds {
            get {
                return ResourceManager.GetString("lbl_upd_sseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update URL.
        /// </summary>
        public static string lbl_upd_url {
            get {
                return ResourceManager.GetString("lbl_upd_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        public static string lbl_update_state {
            get {
                return ResourceManager.GetString("lbl_update_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater is.
        /// </summary>
        public static string lbl_updater_state {
            get {
                return ResourceManager.GetString("lbl_updater_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon to system.
        /// </summary>
        public static string logon {
            get {
                return ResourceManager.GetString("logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your name from users list and enter your password to log in..
        /// </summary>
        public static string logon_process {
            get {
                return ResourceManager.GetString("logon_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Application settings.
        /// </summary>
        public static string mnu_caption_app_settings {
            get {
                return ResourceManager.GetString("mnu_caption_app_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Daily tours.
        /// </summary>
        public static string mnu_caption_daily_tours {
            get {
                return ResourceManager.GetString("mnu_caption_daily_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string mnu_caption_exit {
            get {
                return ResourceManager.GetString("mnu_caption_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string mnu_caption_help {
            get {
                return ResourceManager.GetString("mnu_caption_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        public static string mnu_caption_help_about {
            get {
                return ResourceManager.GetString("mnu_caption_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Content.
        /// </summary>
        public static string mnu_caption_help_content {
            get {
                return ResourceManager.GetString("mnu_caption_help_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Presence.
        /// </summary>
        public static string mnu_caption_presence {
            get {
                return ResourceManager.GetString("mnu_caption_presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Employees.
        /// </summary>
        public static string mnu_caption_staff {
            get {
                return ResourceManager.GetString("mnu_caption_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        public static string mnu_caption_tools {
            get {
                return ResourceManager.GetString("mnu_caption_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tour.
        /// </summary>
        public static string mnu_caption_tour {
            get {
                return ResourceManager.GetString("mnu_caption_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string mnu_caption_tour_report {
            get {
                return ResourceManager.GetString("mnu_caption_tour_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Bills.
        /// </summary>
        public static string mnu_caption_tour_report_monthly {
            get {
                return ResourceManager.GetString("mnu_caption_tour_report_monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User settings.
        /// </summary>
        public static string mnu_caption_user_settings {
            get {
                return ResourceManager.GetString("mnu_caption_user_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        public static string mnu_new_contact {
            get {
                return ResourceManager.GetString("mnu_new_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonebook.
        /// </summary>
        public static string mnu_phone_book {
            get {
                return ResourceManager.GetString("mnu_phone_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string mnu_tip_app_settings {
            get {
                return ResourceManager.GetString("mnu_tip_app_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit today tours.
        /// </summary>
        public static string mnu_tip_daily_tours {
            get {
                return ResourceManager.GetString("mnu_tip_daily_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        public static string mnu_tip_exit {
            get {
                return ResourceManager.GetString("mnu_tip_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string mnu_tip_help {
            get {
                return ResourceManager.GetString("mnu_tip_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about this application.
        /// </summary>
        public static string mnu_tip_help_about {
            get {
                return ResourceManager.GetString("mnu_tip_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use application.
        /// </summary>
        public static string mnu_tip_help_content {
            get {
                return ResourceManager.GetString("mnu_tip_help_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees worktime report.
        /// </summary>
        public static string mnu_tip_presence {
            get {
                return ResourceManager.GetString("mnu_tip_presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string mnu_tip_staff {
            get {
                return ResourceManager.GetString("mnu_tip_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string mnu_tip_tools {
            get {
                return ResourceManager.GetString("mnu_tip_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string mnu_tip_tour {
            get {
                return ResourceManager.GetString("mnu_tip_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string mnu_tip_tour_report {
            get {
                return ResourceManager.GetString("mnu_tip_tour_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string mnu_tip_tour_report_monthly {
            get {
                return ResourceManager.GetString("mnu_tip_tour_report_monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string mnu_tip_user_settings {
            get {
                return ResourceManager.GetString("mnu_tip_user_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string mnu_upd_check_now {
            get {
                return ResourceManager.GetString("mnu_upd_check_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install update.
        /// </summary>
        public static string mnu_upd_install {
            get {
                return ResourceManager.GetString("mnu_upd_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update.
        /// </summary>
        public static string mnu_upd_update {
            get {
                return ResourceManager.GetString("mnu_upd_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record will be deleted permanently. Are you sure you want to remove this item?.
        /// </summary>
        public static string msg_del_confirm_text {
            get {
                return ResourceManager.GetString("msg_del_confirm_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        public static string msg_del_confirm_title {
            get {
                return ResourceManager.GetString("msg_del_confirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available to download.
        /// </summary>
        public static string new_version_exists {
            get {
                return ResourceManager.GetString("new_version_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is ready to install.
        /// </summary>
        public static string new_version_is_ready_to_install {
            get {
                return ResourceManager.GetString("new_version_is_ready_to_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string old_password {
            get {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is up to date.
        /// </summary>
        public static string program_is_up_to_date {
            get {
                return ResourceManager.GetString("program_is_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string rep_monthly_bill_col_day {
            get {
                return ResourceManager.GetString("rep_monthly_bill_col_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrechnung für den Monat.
        /// </summary>
        public static string rep_monthly_bill_title {
            get {
                return ResourceManager.GetString("rep_monthly_bill_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role_name {
            get {
                return ResourceManager.GetString("role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move mouse pointer over a role name to see or edit it&apos;s tasks or select a role to edit it&apos;s name..
        /// </summary>
        public static string select_role {
            get {
                return ResourceManager.GetString("select_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move mouse pointer over a user to see it&apos;s details or select a user to edit..
        /// </summary>
        public static string select_user {
            get {
                return ResourceManager.GetString("select_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type is not selected. Please choose a type and try again..
        /// </summary>
        public static string stat_err_type_empty {
            get {
                return ResourceManager.GetString("stat_err_type_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying updates.
        /// </summary>
        public static string stat_upd_applying {
            get {
                return ResourceManager.GetString("stat_upd_applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for new version.
        /// </summary>
        public static string stat_upd_checking {
            get {
                return ResourceManager.GetString("stat_upd_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading updates....
        /// </summary>
        public static string stat_upd_downloading {
            get {
                return ResourceManager.GetString("stat_upd_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available to download. Click here to download it..
        /// </summary>
        public static string stat_upd_exists {
            get {
                return ResourceManager.GetString("stat_upd_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete. Ready to install update..
        /// </summary>
        public static string stat_upd_ready_to_install {
            get {
                return ResourceManager.GetString("stat_upd_ready_to_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is up to date..
        /// </summary>
        public static string stat_upd_up_to_date {
            get {
                return ResourceManager.GetString("stat_upd_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string tab_title_members {
            get {
                return ResourceManager.GetString("tab_title_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string tab_title_Payments {
            get {
                return ResourceManager.GetString("tab_title_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string tab_title_staff {
            get {
                return ResourceManager.GetString("tab_title_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string tab_title_tour {
            get {
                return ResourceManager.GetString("tab_title_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string tasks {
            get {
                return ResourceManager.GetString("tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check now.
        /// </summary>
        public static string update_check_now {
            get {
                return ResourceManager.GetString("update_check_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string update_download_now {
            get {
                return ResourceManager.GetString("update_download_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string update_install_now {
            get {
                return ResourceManager.GetString("update_install_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string update_install_service {
            get {
                return ResourceManager.GetString("update_install_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string update_remove_service {
            get {
                return ResourceManager.GetString("update_remove_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater service is installed.
        /// </summary>
        public static string updater_is_installed {
            get {
                return ResourceManager.GetString("updater_is_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater service is not installed.
        /// </summary>
        public static string updater_is_not_installed {
            get {
                return ResourceManager.GetString("updater_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is disabled.
        /// </summary>
        public static string user_is_disabled {
            get {
                return ResourceManager.GetString("user_is_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is enabled.
        /// </summary>
        public static string user_is_enabled {
            get {
                return ResourceManager.GetString("user_is_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;UserName.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit your contacts..
        /// </summary>
        public static string wbi_desc_addressbook {
            get {
                return ResourceManager.GetString("wbi_desc_addressbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see daily tours and services schedules and details..
        /// </summary>
        public static string wbi_desc_calendar {
            get {
                return ResourceManager.GetString("wbi_desc_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to adjust settings..
        /// </summary>
        public static string wbi_desc_floppy {
            get {
                return ResourceManager.GetString("wbi_desc_floppy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to read your messages..
        /// </summary>
        public static string wbi_desc_notepad {
            get {
                return ResourceManager.GetString("wbi_desc_notepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to generate reports..
        /// </summary>
        public static string wbi_desc_reports {
            get {
                return ResourceManager.GetString("wbi_desc_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to search in tours..
        /// </summary>
        public static string wbi_desc_search {
            get {
                return ResourceManager.GetString("wbi_desc_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit your work hours..
        /// </summary>
        public static string wbi_desc_workhours {
            get {
                return ResourceManager.GetString("wbi_desc_workhours", resourceCulture);
            }
        }
    }
}
